# This file defines the "workspaces" in our monorepo.
packages:
  - 'apps/*'
  - 'packages/*'
catalogs:
  prisma:
    prisma: latest
  zod:
    zod: latest
  typescript:
    typescript: ^5.7.3
  '@types/node':
    '@types/node': ^24.6.0
  prettier:
    prettier: ^3.6.2
  eslint:
    eslint: ^9.36.0
  '@eslint/js':
    '@eslint/js': ^9.36.0
  
