import { IsString, IsDefined, IsDate, IsOptional } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Student } from "./";

export class Attendance {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    date!: Date;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    status!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    notes?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsDefined()
    @ApiProperty({ type: () => Student })
    student!: Student;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    studentId!: string;
}
