import { IsString, IsDefined, IsOptional, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { User, StudentBatch, Payment } from "./";

export class Batch {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    name!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    subject?: string | null;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    teacher?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    start_date!: Date;

    @IsOptional()
    @ApiProperty({ type: "string", format: "date-time", required: false })
    @IsDate()
    end_date?: Date | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    tutorId?: string | null;

    @IsOptional()
    @ApiProperty({ required: false, type: () => User })
    tutor?: User | null;

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => StudentBatch })
    students!: StudentBatch[];

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => Payment })
    payments!: Payment[];
}
