import { IsString, IsDefined, IsOptional, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Student } from "./";

export class Guardian {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    first_name!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    last_name!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    email!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    phone?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => Student })
    students!: Student[];
}
