import { IsString, IsDefined, IsNumber, IsDate, IsOptional } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Student, Batch } from "./";

export class Payment {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "number" })
    @IsNumber()
    amount!: number;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    payment_date!: Date;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    method!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    notes?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsDefined()
    @ApiProperty({ type: () => Student })
    student!: Student;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    studentId!: string;

    @IsOptional()
    @ApiProperty({ required: false, type: () => Batch })
    batch?: Batch | null;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    batchId?: string | null;
}
