import { IsString, IsDefined, IsOptional, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { User } from "./";

export class RefreshToken {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    hashed_token!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    user_agent?: string | null;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    ip?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    expires_at!: Date;

    @IsOptional()
    @ApiProperty({ type: "string", format: "date-time", required: false })
    @IsDate()
    revoked_at?: Date | null;

    @IsDefined()
    @ApiProperty({ type: () => User })
    user!: User;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    userId!: string;
}
