import { IsString, IsDefined, IsOptional, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Guardian, StudentBatch, Payment, Attendance } from "./";

export class Student {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    first_name!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    last_name!: string;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    email?: string | null;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    phone?: string | null;

    @IsOptional()
    @ApiProperty({ type: "string", required: false })
    @IsString()
    school_name?: string | null;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsDefined()
    @ApiProperty({ type: () => Guardian })
    guardian!: Guardian;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    guardianId!: string;

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => StudentBatch })
    batches!: StudentBatch[];

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => Payment })
    payments!: Payment[];

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => Attendance })
    attendances!: Attendance[];
}
