import { IsString, IsDefined, IsNumber, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Student, Batch } from "./";

export class StudentBatch {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: () => Student })
    student!: Student;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    studentId!: string;

    @IsDefined()
    @ApiProperty({ type: () => Batch })
    batch!: Batch;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    batchId!: string;

    @IsDefined()
    @ApiProperty({ example: 0, type: "number" })
    @IsNumber()
    total_fee_agreed!: number;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    join_date!: Date;
}
