import { IsString, IsDefined, IsIn, IsDate } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";
import { Batch, RefreshToken } from "./";
import { getEnumValues } from "../helpers";
import { UserRole } from "../enums";

export class User {
    @IsDefined()
    @ApiProperty({ example: 'Generated by uuid', type: "string" })
    @IsString()
    id!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    email!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    first_name!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    last_name!: string;

    @IsDefined()
    @ApiProperty({ type: "string" })
    @IsString()
    password!: string;

    @IsDefined()
    @ApiProperty({ example: "STAFF", enum: Object.values(UserRole) })
    @IsIn(getEnumValues(UserRole))
    role!: UserRole;

    @IsDefined()
    @ApiProperty({ example: 'Generated by now', type: "string", format: "date-time" })
    @IsDate()
    created_at!: Date;

    @IsDefined()
    @ApiProperty({ type: "string", format: "date-time" })
    @IsDate()
    updated_at!: Date;

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => Batch })
    batches!: Batch[];

    @IsDefined()
    @ApiProperty({ isArray: true, type: () => RefreshToken })
    refresh_tokens!: RefreshToken[];
}
