// This file was auto-generated by prisma-generator-typescript-interfaces

enum UserRole {
  ADMIN = "ADMIN",
  STAFF = "STAFF"
}

export type User = {
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  password_hash: string;
  role: UserRole;
  created_at: Date;
  updated_at: Date;
  batches?: Batch[];
  refresh_tokens?: RefreshToken[];
};

export type RefreshToken = {
  id: string;
  hashed_token: string;
  user_agent: string | null;
  ip: string | null;
  created_at: Date;
  expires_at: Date;
  revoked_at: Date | null;
  user?: User;
  userId: string;
};

export type Guardian = {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  created_at: Date;
  updated_at: Date;
  students?: Student[];
};

export type Student = {
  id: string;
  first_name: string;
  last_name: string;
  email: string | null;
  phone: string | null;
  school_name: string | null;
  created_at: Date;
  updated_at: Date;
  guardian?: Guardian;
  guardianId: string;
  batches?: StudentBatch[];
  payments?: Payment[];
  attendances?: Attendance[];
};

export type Batch = {
  id: string;
  name: string;
  subject: string | null;
  teacher: string | null;
  start_date: Date;
  end_date: Date | null;
  created_at: Date;
  updated_at: Date;
  tutorId: string | null;
  tutor?: User | null;
  students?: StudentBatch[];
  payments?: Payment[];
};

export type StudentBatch = {
  id: string;
  student?: Student;
  studentId: string;
  batch?: Batch;
  batchId: string;
  total_fee_agreed: number;
  join_date: Date;
};

export type Payment = {
  id: string;
  amount: number;
  payment_date: Date;
  method: string;
  notes: string | null;
  created_at: Date;
  updated_at: Date;
  student?: Student;
  studentId: string;
  batch?: Batch | null;
  batchId: string | null;
};

export type Attendance = {
  id: string;
  date: Date;
  status: string;
  notes: string | null;
  created_at: Date;
  updated_at: Date;
  student?: Student;
  studentId: string;
};
