/* eslint-disable */
// prettier-ignore
// This file is auto-generated by vite-plugin-file-routes.
// Do not edit this file directly.
//
// @ts-nocheck
import React from 'react';
import * as ReactRouter from 'react-router';

export const routes = [{
    path: '/',
    children: [
{
      path: '',
      lazy: async () => {
        const m = await import('./pages/page.tsx');
        return { Component: m.default, ...m };
      },
    },
{
      path: 'posts',
      children: [
{
        path: ':slug',
        lazy: async () => {
          const m = await import('./pages/posts/[slug].tsx');
          return { Component: m.default, ...m };
        },
      }
      ],
    },
{
      lazy: async () => {
        const m = await import('./pages/(auth)/_layout.tsx');
        return { Component: m.default, ...m };
      },
      children: [
{
        path: 'signin',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(auth)/signin/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      }
      ],
    },
{
      path: '*',
      lazy: async () => {
        const m = await import('./pages/404.tsx');
        return { Component: m.default, ...m };
      },
    }
    ],
  }] as ReactRouter.RouteObject[];
