/* eslint-disable */
// prettier-ignore
// This file is auto-generated by vite-plugin-file-routes.
// Do not edit this file directly.
//
// @ts-nocheck
import React from 'react';
import * as ReactRouter from 'react-router';

export const routes = [{
    path: '/',
    lazy: async () => {
      const m = await import('./pages/_app.tsx');
      return { Component: m.default, ...m };
    },
    children: [
{
      path: '',
      lazy: async () => {
        const m = await import('./pages/page.tsx');
        return { Component: m.default, ...m };
      },
    },
{
      lazy: async () => {
        const m = await import('./pages/(auth)/_layout.tsx');
        return { Component: m.default, ...m };
      },
      children: [
{
        path: 'signup',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(auth)/signup/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      },
{
        path: 'signin',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(auth)/signin/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      },
{
        path: 'forgot-password',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(auth)/forgot-password/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      }
      ],
    },
{
      lazy: async () => {
        const m = await import('./pages/(app)/_layout.tsx');
        return { Component: m.default, ...m };
      },
      children: [
{
        path: 'students',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(app)/students/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      },
{
        path: 'batches',
        children: [
{
          path: '',
          lazy: async () => {
            const m = await import('./pages/(app)/batches/page.tsx');
            return { Component: m.default, ...m };
          },
        }
        ],
      }
      ],
    },
{
      path: '*',
      lazy: async () => {
        const m = await import('./pages/404.tsx');
        return { Component: m.default, ...m };
      },
    }
    ],
  }] as ReactRouter.RouteObject[];
